//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace ArmagetronMapEditor.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Resource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Map mapField;
        
        private ResourceType typeField;
        
        private string nameField;
        
        private string versionField;
        
        private string authorField;
        
        private string categoryField;
        
        private string comissionerField;
        
        public Resource() {
            this.typeField = ResourceType.aamap;
            this.versionField = "1.0";
            this.authorField = "Anonymous";
            this.categoryField = "unsorted";
        }
        
        /// <remarks/>
        public Map Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("Map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ResourceType.aamap)]
        public ResourceType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1.0")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Anonymous")]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("unsorted")]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string comissioner {
            get {
                return this.comissionerField;
            }
            set {
                this.comissionerField = value;
                this.RaisePropertyChanged("comissioner");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Map : object, System.ComponentModel.INotifyPropertyChanged {

        private ObservableCollection<Setting> settingsField;
        
        private World worldField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable=false)]
        public ObservableCollection<Setting> Settings {
            get {
                if (settingsField == null) {
                    settingsField = new ObservableCollection<Setting>();
                }
                return this.settingsField;
            }
            set {
                this.settingsField = value;
                this.RaisePropertyChanged("Settings");
            }
        }
        
        /// <remarks/>
        public World World {
            get {
                return this.worldField;
            }
            set {
                this.worldField = value;
                this.RaisePropertyChanged("World");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Setting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class World : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Field fieldField;
        
        /// <remarks/>
        public Field Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Field : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Axes axesField;
        
        private ObservableCollection<object> itemsField;
        
        private FieldLogicalBox logicalBoxField;
        
        public Field() {
            this.logicalBoxField = FieldLogicalBox.@true;
        }
        
        /// <remarks/>
        public Axes Axes {
            get {
                return this.axesField;
            }
            set {
                this.axesField = value;
                this.RaisePropertyChanged("Axes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Spawn", typeof(Spawn))]
        [System.Xml.Serialization.XmlElementAttribute("Wall", typeof(Wall))]
        [System.Xml.Serialization.XmlElementAttribute("Zone", typeof(Zone))]
        public ObservableCollection<object> Items {
            get {
                if (itemsField == null) {
                    itemsField = new ObservableCollection<object>();
                }
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FieldLogicalBox.@true)]
        public FieldLogicalBox logicalBox {
            get {
                return this.logicalBoxField;
            }
            set {
                this.logicalBoxField = value;
                this.RaisePropertyChanged("logicalBox");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Axes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObservableCollection<Axis> axisField;
        
        private string numberField;
        
        private AxesNormalize normalizeField;
        
        public Axes() {
            this.numberField = "4";
            this.normalizeField = AxesNormalize.@true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Axis")]
        public ObservableCollection<Axis> Axis {
            get {
                return this.axisField;
            }
            set {
                this.axisField = value;
                this.RaisePropertyChanged("Axis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("4")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AxesNormalize.@true)]
        public AxesNormalize normalize {
            get {
                return this.normalizeField;
            }
            set {
                this.normalizeField = value;
                this.RaisePropertyChanged("normalize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Axis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double xdirField;
        
        private bool xdirFieldSpecified;
        
        private double ydirField;
        
        private bool ydirFieldSpecified;
        
        private double angleField;
        
        private bool angleFieldSpecified;
        
        private double lengthField;
        
        public Axis() {
            this.lengthField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double xdir {
            get {
                return this.xdirField;
            }
            set {
                this.xdirField = value;
                this.RaisePropertyChanged("xdir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xdirSpecified {
            get {
                return this.xdirFieldSpecified;
            }
            set {
                this.xdirFieldSpecified = value;
                this.RaisePropertyChanged("xdirSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ydir {
            get {
                return this.ydirField;
            }
            set {
                this.ydirField = value;
                this.RaisePropertyChanged("ydir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ydirSpecified {
            get {
                return this.ydirFieldSpecified;
            }
            set {
                this.ydirFieldSpecified = value;
                this.RaisePropertyChanged("ydirSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
                this.RaisePropertyChanged("angle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool angleSpecified {
            get {
                return this.angleFieldSpecified;
            }
            set {
                this.angleFieldSpecified = value;
                this.RaisePropertyChanged("angleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    public enum AxesNormalize {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Spawn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double xField;
        
        private double yField;
        
        private double xdirField;
        
        private bool xdirFieldSpecified;
        
        private double ydirField;
        
        private bool ydirFieldSpecified;
        
        private double angleField;
        
        private bool angleFieldSpecified;
        
        private double lengthField;
        
        public Spawn() {
            this.lengthField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double xdir {
            get {
                return this.xdirField;
            }
            set {
                this.xdirField = value;
                this.RaisePropertyChanged("xdir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xdirSpecified {
            get {
                return this.xdirFieldSpecified;
            }
            set {
                this.xdirFieldSpecified = value;
                this.RaisePropertyChanged("xdirSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ydir {
            get {
                return this.ydirField;
            }
            set {
                this.ydirField = value;
                this.RaisePropertyChanged("ydir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ydirSpecified {
            get {
                return this.ydirFieldSpecified;
            }
            set {
                this.ydirFieldSpecified = value;
                this.RaisePropertyChanged("ydirSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
                this.RaisePropertyChanged("angle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool angleSpecified {
            get {
                return this.angleFieldSpecified;
            }
            set {
                this.angleFieldSpecified = value;
                this.RaisePropertyChanged("angleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Wall : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObservableCollection<Point> pointField;
        
        private double heightField;
        
        private bool heightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public ObservableCollection<Point> Point {
            get {
                if (this.pointField == null) {
                    this.pointField = new ObservableCollection<Point>();
                }
                return this.pointField;
            }
            set {
                this.pointField = value;
                this.RaisePropertyChanged("Point");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Point : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double xField;
        
        private double yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Zone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ShapeCircle shapeCircleField;
        
        private ZoneEffect effectField;
        
        public Zone() {
            this.effectField = ZoneEffect.death;
        }
        
        /// <remarks/>
        public ShapeCircle ShapeCircle {
            get {
                return this.shapeCircleField;
            }
            set {
                this.shapeCircleField = value;
                this.RaisePropertyChanged("ShapeCircle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ZoneEffect.death)]
        public ZoneEffect effect {
            get {
                return this.effectField;
            }
            set {
                this.effectField = value;
                this.RaisePropertyChanged("effect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class ShapeCircle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Point pointField;
        
        private double radiusField;
        
        /// <remarks/>
        public Point Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
                this.RaisePropertyChanged("Point");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
                this.RaisePropertyChanged("radius");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    public enum ZoneEffect {
        
        /// <remarks/>
        win,
        
        /// <remarks/>
        death,
        
        /// <remarks/>
        fortress,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    public enum FieldLogicalBox {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    public enum ResourceType {
        
        /// <remarks/>
        aamap,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class Settings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObservableCollection<Setting> settingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Setting")]
        public ObservableCollection<Setting> Setting {
            get {
                if (settingField == null) {
                    settingField = new ObservableCollection<Setting>();
                }
                return this.settingField;
            }
            set {
                this.settingField = value;
                this.RaisePropertyChanged("Setting");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
